### ISSUE TITLE
zerotier-cli peers reports negative latency

### ISSUE THREAD

**Issue by rokleM** [zerotier/ZeroTierOne#1042]
Not sure if this is the right place to report (or even if it is a valid report) but here it goes:

I run `zerotier-cli peers` and I get:

    200 peers
    <ztaddr>   <ver>  <role> <lat> <link> <lastTX> <lastRX> <path>
    0270e9004f 1.4.6  LEAF      -1 DIRECT 3594     4308     67.11.216.155/13619
    34e0a5e174 -      PLANET  -368 DIRECT 3610     3970     147.75.92.2/443
    357a1d8d5b 1.4.6  LEAF    -668 DIRECT 3264     3264     89.197.203.18/61663
    f6e3bbee15 1.4.2  LEAF       2 DIRECT 3614     3612     192.168.0.140/9993
    3a46f1bf30 -      PLANET    -1 DIRECT 6042     5634     185.180.13.82/9993
    778cde7190 -      PLANET  -736 DIRECT 11654    1146     103.195.103.66/9993
    992fcf1db7 -      PLANET  -532 DIRECT 6042     942      195.181.173.159/9993

Which includes negative latencies.

Seeing the code, I see there's a conversion from an `unsigned int` to an `int` in [Node.cpp](https://github.com/zerotier/ZeroTierOne/blob/91b16310ea47a6de96edb488a61494f8ed8c139c/node/Node.cpp#L474), but it does not seem to be possible for it to generate a negative value.

Is this correct? If so, how do I need to interpret those negative values?

**Comment by glimberg** [comment]
We figured out time travel.  Shh!  Don't tell anyone!

**Comment by hzhwcmhf** [comment]
Some times lastTX and lastRX is also negative

**Comment by joseph-henry** [comment]
This is resolved in 2.0

**Comment by PaleNeutron** [comment]
@joseph-henry , hello, almost 3 years later, this seems not fixed and where is 2.0 ?

**Comment by joseph-henry** [comment]
I don't remember the history for this specific fix or lack thereof. I'll re-open this since the 1.X branch will be in use longer than we anticipated when the comment was made. I'll take a look tomorrow.

**Comment by joseph-henry** [comment]
After reviewing the code it seems that this is correct behavior and not the result of an integer overflow (the latency is intentionally set to this value when its actual value is outside of reasonable bounds). The `-1` should be interpreted as "no data".

**Comment by rokleM** [comment]
I think a -1 would be OK, thing is the latency reported is not -1 it's a negative number ...does not seem right!

An example from `zerotier-cli listpeers`:

    200 listpeers <ztaddr> <path> <latency> <version> <role>                                                                                                                                                                                     
    200 listpeers 024bf64b52 45.167.134.1/55781;376862;232662 -808 1.4.6 LEAF                                                                                                                                                                    
    200 listpeers 0270d9004f 67.17.206.155/23316;178;178 -536 1.10.1 LEAF                                                                                                                                                                        
    200 listpeers 0ef70810bc 67.17.206.155/63022;7608;11596 358 1.10.1 LEAF                                                                                                                                                                      
    200 listpeers 0f4b1bb633 213.215.166.254/50317;7166;6680 928 1.6.5 LEAF

**Comment by joseph-henry** [comment]
Oh you're absolutely right. I focused on the `-1`s only. Hmm. What version is that output from?

**Comment by rokleM** [comment]
`ZeroTier One version 1.10.2 build 0 (platform 2 arch 2) `
