### ISSUE TITLE
DNS push with 1.6.2 on IOS still does not work

### ISSUE THREAD

**Issue by cyberbix** [zerotier/ZeroTierOne#1315]
No DNS Servers appear at all when configuring "Network DNS", tested with several IOS versions and devices. Seem´s not to matter which IOS and which IOS device.

Testing the same network ID with 1.6.2 on Android works fine.

Pinging the name server and scanning port 53 works on the IOS device.

**Comment by laduke** [comment]
Should be fixed. iOS is up to 1.6.5 now.

**Comment by bronislav** [comment]
I have 1.6.6 on my iPhone and DNS push still don't work. Not sure how to debug this.

**Comment by erikh** [comment]
My family uses a seafile instance against ios devices that use this feature along with zerotier/zeronsd. Please check out the zerotier blog for more information on how to configure this properly, as I turned it into a post there.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by erikh** [comment]
Also, be aware that private relay in iOS 15 interferes with DNS resolution as well as other things that may be interfering with zerotier, so be sure it is turned off.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by 1player** [comment]
Still broken in the latest iOS version

**Comment by unizhu** [comment]
Still cannot get DNS with version 1.8.10 on iOS 16.5

**Comment by jducifuentes** [comment]
still the same, ios 16.1.1 zerotier 1.8.10

**Comment by laduke** [comment]
Hello, it's working on my phone. The DNS servers field does not populate with anything, but pinging stuff by name works.

**Comment by jducifuentes** [comment]
Could you post your config?

Thanks

**Comment by laduke** [comment]
the network config? It just has like
```
    "dns": {
      "domain": "cacti",
      "servers": [
        "10.2.0.2"
      ]
    },
```
