### ISSUE TITLE
Multipath balance-aware makes zerotier unresponsive

### ISSUE THREAD

**Issue by grapexy** [zerotier/ZeroTierOne#1764]
Continuing issue first noted in https://github.com/zerotier/ZeroTierOne/issues/1745#issuecomment-1275637322

Zerotier becomes unresponsive when balance-aware mode is used after changes made by the latest commit on dev branch (https://github.com/zerotier/ZeroTierOne/commit/e1f60e3).

I believed this was related to a FreeBSD peer, but it also happens between linux peers.

Repro:

1. Configure 2 linux peers with `balance-aware` bonding policy:
```
{
    "physical": {},
    "settings": {
        "allowSecondaryPort": false,
        "interfacePrefixBlacklist": [],
        "allowTcpFallbackRelay": false,
        "portMappingEnabled": false,
        "defaultBondingPolicy": "balance-aware"
    }
}
```
2. Ping peer2 from peer1.

Expected: Packets should be sent, zerotier should continue functioning.

Actual: 
1. After a few delivered packets (~6), zerotier becomes unresponsive, all packets are lost (destination unreachable).
2. `zerotier-cli status` hangs indefinitely on both peers.
3. ZT is unreachable for all subsequent packets until it's restarted.

Relevant logs:

Peer 1:
```
2022-10-12 23:31:36 (peer2/balance-aware) new default bond
2022-10-12 23:31:36 (peer2/balance-aware) starting bond
...
2022-10-12 23:31:36 (peer2/balance-aware) bond: bp=5, fi=5000, mi=1666, ud=0, dd=0, flows=0, leaf=1, overhead=0.000000 KB/s, links=(4/4)
2022-10-12 23:31:36 (peer2/balance-aware) path[ 0] --- alive (in     518, out:      61),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth1/peer2_ip/9993) spare=0
2022-10-12 23:31:36 (peer2/balance-aware) path[ 1] --- alive (in    3241, out:      61),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth2/peer2_ip/9993) spare=0
2022-10-12 23:31:36 (peer2/balance-aware) path[ 2] --- alive (in    3197, out:      61),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth4/peer2_ip/9993) spare=0
2022-10-12 23:31:36 (peer2/balance-aware) path[ 3] --- alive (in    3169, out:      61),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth3/peer2_ip/9993) spare=0
2022-10-12 23:31:36 (peer2/balance-aware) 
2022-10-12 23:31:38 (peer2/balance-aware) attempting to assign flow for the first time
2022-10-12 23:31:38 (peer2/balance-aware) assign out-flow 50f3 to link  (1 / 1 flows)

```
Peer 2:

```
2022-10-12 21:31:37 (peer1/balance-aware) new default bond
2022-10-12 21:31:37 (peer1/balance-aware) starting bond
...
2022-10-12 21:31:37 (peer1/balance-aware) bond: bp=5, fi=5000, mi=1666, ud=0, dd=0, flows=0, leaf=1, overhead=0.000000 KB/s, links=(4/4)
2022-10-12 21:31:37 (peer1/balance-aware) path[ 0] --- alive (in     548, out:      60),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth0/peer_1_ip_1/19410) spare=0
2022-10-12 21:31:37 (peer1/balance-aware) path[ 1] --- alive (in     543, out:      60),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth0/peer_1_ip_2/52825) spare=0
2022-10-12 21:31:37 (peer1/balance-aware) path[ 2] --- alive (in     486, out:      60),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth0/peer_1_ip_3/26638) spare=0
2022-10-12 21:31:37 (peer1/balance-aware) path[ 3] --- alive (in     519, out:      60),   eligible,   bonded, flows=0      lat=0.000    pdv=0.000   err=0.0000 loss=0.0000 qual=0.0000 --- (redacted-eth0/peer_1_ip_3/16862) spare=0
2022-10-12 21:31:37 (peer1/balance-aware) 
2022-10-12 21:31:37 (peer1/balance-aware) attempting to assign flow for the first time
2022-10-12 21:31:37 (peer1/balance-aware) assign out-flow 50f3 to link  (1 / 1 flows)
```

Logging ends completely in both cases and zt becomes unreachable as soon as out-flow assignments happen on the last log line.

`balance-xor` does not seem to be affected from my testing, only `balance-aware`.

**Comment by grapexy** [comment]
@joseph-henry I'll piggy back on this to point out another issue with latest bonding changes (very excited about latest developments here, by the way).

https://github.com/zerotier/ZeroTierOne/commit/bc521504caa759dbd38c5e16ab4c2b1a5d0d9d3b introduced a bug where `zerotier-cli bond list` command outputs no data (checked on linux and FreeBSD):

```
$ zerotier-cli bond list
    <peer>                        <bondtype>     <links>
      NONE				NONE	    NONE       NONE

$ zerotier-cli -j bond list
{
 "apiVersion": 4,
 "clock": 1665627206979,
 "controller": true,
 "databaseReady": true
}
```

However, `zerotier-cli bond peer_id show` works and new output is great!:
```
Peer                   : {redacted_peer_id}
Bond                   : balance-aware
Link Select Method     : 0
Links                  : 4/4
Failover Interval (ms) : 5000
Up Delay (ms)          : 0
Down Delay (ms)        : 0
Packets Per Link       : 0

idx                  interface                                  path               socket
----------------------------------------------------------------------------------------------------
 0:                       eth0                                 {redacted_ip_1}/16278 {redacted_socket_id}
 1:                       eth0                                   {redacted_ip_2}/43007 {redacted_socket_id}
 2:                       eth0                                 {redacted_ip_3}/26641 {redacted_socket_id}
 3:                       eth0                                 {redacted_ip_4}/16775 {redacted_socket_id}

idx     lat      pdv     plr     per    speed  alloc      rx_age      tx_age  eligible  bonded
----------------------------------------------------------------------------------------------------
 0:    34.00     1.00  0.0000  0.0000       0   0.35           0           0         1       1
 1:    37.00     1.00  0.0000  0.0000       0   0.33           0           0         1       1
 2:   110.00     9.00  0.0000  0.0000       0   0.17           0           0         1       1
 3:    65.00     4.00  0.0000  0.0000       0   0.15           5           3         1       1
```

This is a minor issue, as `bond show` is more than enough, but pointed this out just in case.

**Comment by joseph-henry** [comment]
Thanks for this. I'm curious why a ping would be creating a flow since there is no port associated with that. It should assign to a random interface. What kind of "ping" is this? I'll take a look look at the `list bonds` issue next.

**Comment by grapexy** [comment]
Tested the latest dev (98b190c) and unresponsiveness issue is resolved, but now it looks like that there are issues with flow assignment / persistence. The log is flooded with `attempting to assign flow for the first time` entries, the latency shoots up to ~400ms and throughput is 10% of the link.

**Comment by unixfox** [comment]
Can replicate the bug too. Zerotier becomes unresponsive and use 100% of the CPU.
Using zerotier 1.10.2

**Comment by GeorgeLubaretsi** [comment]
This is still an issue on ZT 1.10.6.

Getting a lot of `attempting to assign flow for the first time` in log.

**Comment by joseph-henry** [comment]
Hmm, interesting. I don't see it. Are there details unique to your setup I could use to replicate?

**Comment by GeorgeLubaretsi** [comment]
ZT debian peer (1.10.6) that acts as the gateway for external connections from local network:

```
{
    "physical": {},
    "settings": {
        "allowSecondaryPort": false,
        "interfacePrefixBlacklist": [
            "eth0"
        ],
        "allowTcpFallbackRelay": true,
        "portMappingEnabled": false,
        "defaultBondingPolicy": "custom-balance-aware",
        "policies": {
            "custom-balance-aware": {
                "basePolicy": "balance-aware",
                "links": {
                    "eth1": {
                        "mode": "primary"
                    },
                    "eth2": {
                        "mode": "primary"
                    },
                    "eth3": {
                        "mode": "spare"
                    },
                    "eth4": {
                        "mode": "spare"
                    }
                }
            }
        }
    }
}
```

Couple of routing rules, but nothing out of ordinary:

```
iface zt inet static
	address 10.244.0.2/23
	up ip route add default via 10.244.1.1
	up ip route del 10.244.0.0/23
	up ip route add 10.244.0.0/23 dev zt
	up ip route add 10.244.0.0/23 dev zt table 100
	up ip route add default via 10.244.1.1 table 100
	up ip rule add from 192.168.0.0/16 lookup 100

```
---

Edge peer (freebsd - zt 1.10.4) that acts as an exit node, to which all traffic is routed from debian peer:
```
{
    "physical": {},
    "settings": {
        "allowSecondaryPort": false,
        "interfacePrefixBlacklist": [
            "wg"
        ],
        "portMappingEnabled": false,
        "allowTcpFallbackRelay": false,
        "defaultBondingPolicy": "balance-aware"
    }
}
```

Everything works properly in this configuration up until and including bc521504c, but breaks after that, with no configuration changes.

**Comment by joseph-henry** [comment]
Thank you, I'll take another look.

**Comment by grapexy** [comment]
@joseph-henry Any progress on this? Can I help by gathering / providing more data or by any other means?

**Comment by grapexy** [comment]
@joseph-henry Same issue on 1.12.0.

This is the log being flooded with flow assignments. It looks like ZT has issues keeping the flow on the same link in balance-aware configuration.

```2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) assign out-flow aa85 to link  (795 / 797 flows)
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) assign out-flow ea79 to link  (796 / 798 flows)
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) assign out-flow 80e3 to link  (797 / 799 flows)
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:38 (c033336e1a/custom-balance-aware) assign out-flow 87d6 to link  (798 / 800 flows)
2023-08-24 12:09:40 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:40 (c033336e1a/custom-balance-aware) assign out-flow 9ced to link  (799 / 801 flows)
2023-08-24 12:09:41 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:41 (c033336e1a/custom-balance-aware) assign out-flow 943b to link  (800 / 802 flows)
2023-08-24 12:09:42 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:42 (c033336e1a/custom-balance-aware) assign out-flow 879d to link  (801 / 803 flows)
2023-08-24 12:09:42 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:42 (c033336e1a/custom-balance-aware) assign out-flow b997 to link  (802 / 804 flows)
2023-08-24 12:09:43 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:43 (c033336e1a/custom-balance-aware) assign out-flow 9ce1 to link  (803 / 805 flows)
2023-08-24 12:09:45 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:45 (c033336e1a/custom-balance-aware) assign out-flow 5876 to link  (804 / 806 flows)
2023-08-24 12:09:45 (c033336e1a/custom-balance-aware) attempting to assign flow for the first time
2023-08-24 12:09:45 (c033336e1a/custom-balance-aware) assign out-flow b8df to link  (805 / 807 flows)
```

**Comment by joseph-henry** [comment]
Ok thank you for all of this. I have a test rig up now and I'll try to replicate this in a little bit.

**Comment by grapexy** [comment]
> Ok thank you for all of this. I have a test rig up now and I'll try to replicate this in a little bit.

Please reach out if you need any information and/or private data.

**Comment by grapexy** [comment]
@joseph-henry Wondering if you were able to replicate this issue
