### ISSUE TITLE
"Node ID: unknown" on Windows 10 October (2018) Update

### ISSUE THREAD

**Issue by ElTopo** [zerotier/ZeroTierOne#865]
**Describe the bug**
Microsoft just released Windows 10 October 2018 Update earlier this week. The Windows 10 version:
Version: 1809 (OS Build: 17763.1)
![screenshot - 10_4_2018 6_42_24 pm](https://user-images.githubusercontent.com/217195/46512000-9762e580-c806-11e8-979e-00abe3886a08.png)

Zerotier version: 1.2.12

After I reboot the Windows 10 system, Zerotier got "Node ID: unknown" in pop-up menu:
![screenshot - 10_4_2018 6_40_47 pm](https://user-images.githubusercontent.com/217195/46512054-e872d980-c806-11e8-804e-cc4fdf8d62f9.png)

Click on "Show Networks...", a blank, weird-size window pop-up:
![screenshot - 10_4_2018 6_41_40 pm](https://user-images.githubusercontent.com/217195/46512106-10fad380-c807-11e8-8c69-9bf45ff8ba84.png)

zerotier gets stuck in this state for long time (i.e., serveral hours) and never gets Node ID.
my.zerotier.com shows this system is offline.

Zerotier was working before I updated the Windows 10 system today (10/4/2018).

I have seen this problem on two of my laptops, one is Windows 10 Home, the other is Windows 10 Pro.
 

**To Reproduce**
Not sure if these steps will always reproduce the problem, but...
1. Update Windows 10 to October 2018 Update (1809);
2. reboot the system (the update requires reboot anyway);
3. when system is fully up and running, check Zerotier's status; also check my.zerotier.com for the system's status.

**Expected behavior**
Zerotier Node ID should have been assigned, the system should have joined zerotier network(s) and got zerotier IP(s), the system should have been ONLINE.

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit) Home and Pro
 - OS/Distribution Version: 1809 (OS Build: 17763.1)
 - ZeroTier Version 1.2.12
 - Hardware Windows 10 laptops

**Comment by laduke** [comment]
Thanks for filling that out. I'll try to reproduce. 

Things you could try:
- exit and re-open the tray app
- restart the ZeroTierOne system service in `services.msc`
- open an admin prompt and play with 
  - `zerotier-cli listnetworks`
  -  `zerotier-cli join [network-id]`
  -  `zerotier-cli leave [network-id]`

**Comment by tnewton1** [comment]
I've been testing the latest Windows Insider build and the ZeroTier One client starts as expected, no workaround needed. Maybe this was a bug in Windows 1809?
![winver_2018-12-24_09-52-52](https://user-images.githubusercontent.com/3200699/50402087-c59af600-0761-11e9-8cb8-dcef85294a0e.png)

**Comment by gary-schiltz** [comment]
Any progress on this, maybe in the trunk? I'm not a Windows guy myself, but I've been trying to get clients to switch away from Hamachi, which may not be such a good idea if this remains open.

**Comment by laduke** [comment]
I saw some UI work go by on the `dev` branch, if anyone wants to try it out. I've not built on Windows before, not sure what's required.

**Comment by kiam001** [comment]
I had the same problem after executing the Msi and the repair function works fine again

**Comment by backmanma** [comment]
Our customers are reporting problem as described here when using windows 10 17xx. 

@kiam001 did your resolve this problem using the repair function?

**Comment by kiam001** [comment]
Yes @backmanma

**Comment by glimberg** [comment]
This is fixed in the dev branch.  Just waiting for the powers that be to make a new release

**Comment by ElTopo** [comment]
@glimberg Thanks! waiting for the next release (and hope it'll happen soon)

**Comment by backmanma** [comment]
I tested to build the ZeroTier service from dev branch, but still have problem with unknown id.

**Comment by RainbowDRGN** [comment]
Same problem. Different circumstance. I ran sysprep on my laptop, imaged, and deployed image to my desktop. Started desktop first after image, and it has old laptop Node ID on connecting (same Windows 10 user profile, if it matters). Desktop is connecting to network and seems to work fine. Started laptop and it's also using the pre-sysprep Node ID and shows having the same ZT ip address as desktop. Laptop won't connect to anything via ZTO.

**Comment by lancelon** [comment]
Same problem  - service says "automatic" but doesn't start on boot unless I manually start it

**Comment by marshalleq** [comment]
Well I've got a started service on Windows 10 1809, but it crashes when trying to create a new network and has no networks available to join, nor can I figure out how to enter one manually.  It did ask me for an API when starting, but unfortunately I put in an incorrect value - perhaps it's this, but uninstalling, rebooting, reinstalling doesn't help.  I'm running in QEMU with redhat virt-io - I see someone else also in a VM.

**Comment by unquietwiki** [comment]
Closing issue: ZT 1.4.6 has been out for a good while now; Windows 10 is on 2004; ZT 1.6.0 is pending.
